<?php
/**
 * @copyright Copyright (c) 2024 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);

/**
 * Widget template for displaying a list of CMS pages.
 *
 * @var PageList $block
 * @var Escaper $escaper
 */

use Magebit\PageListWidget\Block\Widget\PageList;
use Magento\Framework\Escaper;

?>
    <h3><?= $escaper->escapeHtml($block->getData('title')) ?></h3>

<ul>
    <?php foreach ($block->getPages() as $page): ?>
        <li>
            <a href="<?= $escaper->escapeUrl($block->getUrl($page->getIdentifier())) ?>">
                <?= $escaper->escapeHtml($page->getTitle()) ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
