<?php
/**
 * @copyright Copyright (c) 2024 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);


use Magebit\Faq\Block\QuestionList;
use Magento\Framework\Escaper;

/**
 * @var QuestionList $block
 * @var Escaper $escaper
 */
$questions = $block->getQuestions();
?>

<div
    id="element"
    data-mage-init='{
        "accordion": {
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "multipleCollapsible": true
        }
    }'
    class="question table">
    <?php foreach ($questions as $question): ?>
        <div data-role="collapsible">
            <div data-role="trigger" class="question title">
                <span><?= $escaper->escapeHtml($question->getQuestion()) ?></span>
            </div>
        </div>
        <div data-role="content" class="question"><?= $escaper->escapeHtml($question->getAnswer()) ?></div>
    <?php endforeach; ?>
</div>

