<?php
/**
 * @copyright Copyright (c) 2024 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);

use Magebit\Learning\Block\Product\View\AddToCart;
use Magento\Framework\Escaper;

/**
 * Template for displaying product stock information, pricing, quantity selector, and upsell products.
 * @var AddToCart $block
 * @var Escaper $escaper
 */
$qty = $block->getProductQty();
$isInStock = $block->isProductInStock();
?>
<div data-bind="scope: 'qtyCounter'">
    <div class="qty-container">
        <div class="qty-counter">
            <button type="button" class="btn-decrease"
                    data-bind="click: decrease"><?= $escaper->escapeHtml(__('--'))?></button>
            <input type="text" data-bind="value: qty, valueUpdate: 'input', event: { change: validateQty }" />
            <button type="button" class="btn-increase"
                    data-bind="click: increase"><?= $escaper->escapeHtml(__('+'))?></button>
        </div>
        <div class="stock-info">
            <span class="stock-icon">
                <img src="<?= $block->getViewFileUrl('Magento_Catalog::images/in_stock.svg') ?>"
                     alt="<?= __('In Stock Icon') ?>" width="11" height="8.005" />
            </span>
            <p>
                <strong class="in-stock-text">
                    <?= $escaper->escapeHtml($isInStock ? __('IN STOCK') : __('OUT OF STOCK')) ?>
                </strong>
                <?php if ($isInStock && $qty > 0): ?>
                    <span><?= $escaper->escapeHtml(__('%1 items available', $qty)) ?></span>
                <?php endif; ?>
            </p>
        </div>
    </div>
</div>
<div class="add-to-cart">
    <button type="button" class="action primary" onclick="location.href='<?= $block->getAddToCartUrl($block->getProduct()) ?>'">
        <?=$escaper->escapeHtml(__('Add to Cart')) ?>
    </button>
</div>
<!-- Knockout.js Component Initialization -->
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "qtyCounter": {
                        "component": "Magento_Catalog/js/qty-counter"
                    }
                }
            }
        }
    }
</script>
