<?php
/**
 * @copyright Copyright (c) 2024 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);
use Magebit\Learning\Block\Product\View\Attributes;
use Magento\Framework\Escaper;
use Magento\Framework\Exception\LocalizedException;

/**
 * Template for displaying selected product attributes and short description.
 * @var Attributes $block
 * @var Escaper $escaper
 */
?>

<div class="product-details">
    <?php $attributes = $block->getDisplayAttributes(); ?>
    <?php if (!empty($attributes)): ?>
        <?php foreach ($attributes as $attribute): ?>
            <div class="detail-item">
                <li>
                    <strong><?= $escaper->escapeHtml($attribute['label']) ?>:</strong>
                    <?= $escaper->escapeHtml($attribute['value']) ?>
                </li>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p><?= $escaper->escapeHtml(__('No additional product information available.')) ?></p>
    <?php endif; ?>

    <?php try {
        if ($block->getShortDescription()): ?>
            <div class="short_description">
                <p><?= $block->getShortDescription() ?></p>
            </div>
        <?php endif;
    } catch (LocalizedException $e) {

    } ?>
</div>
