<?php
/**
 * @copyright Copyright (c) 2024 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);

use Magebit\Learning\Block\Product\View\RelatedProducts;
use Magento\Framework\Escaper;

/**
 * Template for displaying related products in a grid format.
 * @var RelatedProducts $block
 * @var Escaper $escaper
 */

$relatedProducts = $block->getRelatedProducts()
?>

<?php if ($relatedProducts->getSize()): ?>
    <div class="related-products">
        <h2><?= $escaper->escapeHtml(__('Related Products')) ?></h2>
        <hr>
        <ul class="products-grid">
            <?php foreach ($relatedProducts as $product): ?>
                <li class="product-item">
                    <a href="<?= $escaper->escapeUrl($block->getProductUrls($product)) ?>">
                        <img src="<?= $escaper->escapeUrl($block->getProductImageUrl($product)) ?>"
                             alt="<?= $escaper->escapeHtml($block->getProductName($product)) ?>"/>
                        <h3><?= $escaper->escapeHtml($block->getProductName($product)) ?></h3>
                    </a>
                    <div class="product-reviews">
                        <?= /** @noEscape */ $block->getReviewsSummaryHtml($product, 'short', true) ?>
                    </div>
                    <p class="product-price">
                        <?= /** @noEscape */ $block->getPrice($product) ?>
                    </p>
                    <div class="add-to-cart-related">
                        <button type="button" class="action-related"
                                onclick="location.href='<?= $escaper->escapeUrl($block->addToCartUrl($product)) ?>'">
                            <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                        </button>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

